un makefile est un fichier qui permet de lire des regles qui vont generer 
des programmes en compilant seulement les parties modifiées.


syntaxe :

<target> : <pre-requisites>
	<recipe>

----------------------------------------

all: file1   
    cat file1 > file2

file1:
    echo "hello" > file1

$(Var_name) call a variable


-----------------------------------------

clean:
    rm file1 file2 

spécial var :
 $@ -> current target
 $< -> first dependencies
 $^ -> dependencies list
 $? -> dependencies list recently updates
 $* -> file name without his extension







conditions :

ifndef

ifeq ($(var_name), <value>)
	<command>

else
	<command>